name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.8"
        - "3.9"
        - "3.10"
    steps:
      - name: Check out project
        uses: actions/checkout@v2
      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v2
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
          cache: pip
      - name: Install dependencies
        run: pip3 install -r requirements.txt -r test/requirements.txt -r docs/requirements.txt
      - name: Run tests
        run: pre-commit run --all-files
